@startuml
' par défaut, les couches sont disposées dans l'ordre d'apparition
' nous utilison participant pour préciser qu'après Navigateur il y a Vue et non Controleur
participant Navigateur
participant Vue

Navigateur -> Controleur: GET /ajouterEntrainement\n avec idquestionnaire et idCanal
Controleur -> Controleur: Verifie que le idQuestionnaire \n idCanal sont entiers 
Controleur -> Dao:QuestionnaireDao.\n ajouterEntrainement\n(idQuestionnaire, idCanal)
Dao -> SGBD: INSERT ...
SGBD -> Dao:  idEntainement
Dao -> Controleur: idEntrainement
Controleur -> Navigateur: response.sendRedirect\n(entrainements?idcanal=...)

@enduml

/' (commentaire sur plusieurs lignes, comme en Java, avec ' qui remplace *)
1ere étape
Créer le contrôleur et une vue minimale, et tester
Pour cela, créer une servlet monFormulaire Servlet dans fr.siomassy2021.controller, avec
le chemin (utl) /monformulaire.
=> commit

2e étape
Mettre des canaux en dur dans le contrôleur,
et les afficher dans la JSP.
=> commit

3e étape
Appel de la Dao, qui construit la liste en dur
Le memberId est aussi mis en dur à 1
=> commit
'/