 @startuml
' par défaut, les couches sont disposées dans l'ordre d'apparition
' nous utilison participant pour préciser qu'après Navigateur il y a Vue et non Controleur
participant Navigateur
participant Vue

Navigateur -> Controleur: GET /canaux
Controleur -> Dao: CanalDao.getAll()
Dao -> SGBD: SELECT ...
SGBD -> Dao: ca naux trouvés 
Dao -> Controleur: List<Canal>;
Controleur -> Vue: canaux.jsp
Vue -> Navigateur: liste des canaux
@enduml

/' (commentaire sur plusieurs lignes, comme en Java, avec ' qui remplace *)
1ere étape
Créer le contrôleur et une vue minimale, et tester
Pour cela, créer une servlet ListerEFGServlet dans fr.siomassy2021.controller, avec
le chemin (utl) /efgs
=> commit

2e étape
Mettre des EFGs en dur dans le contrôleur,
et les afficher dans la JSP.
=> commit

3e étape
Appel de la Dao, qui construit la liste en dur
Le memberId est aussi mis en dur à 1
=> commit
'/
