 @startuml
' par défaut, les couches sont disposées dans l'ordre d'apparition
' nous utilison participant pour préciser qu'après Navigateur il y a Vue et non Controleur
participant Navigateur
participant Vue

Navigateur -> Controleur: POST /repondreQuestion\n avec idQuestion, reponse 
Controleur -> Controleur: verifie idQuestion est entier\n reponse pas vide
Controleur -> Controleur: id du user en session
Controleur -> Dao: QuestionDao.insertReponse (idQuestion, idPersonne,reponse)
Dao -> SGBD: INSERT INTO reponses_question...
SGBD -> Dao:  ok ou exception
Dao -> Controleur: ok ou exception
Controleur -> Navigateur:  response.sendRedirect("reponsesQuestion")
Vue -> Navigateur: reponsesQuestion
@enduml

/' (commentaire sur plusieurs lignes, comme en Java, avec ' qui remplace *)
1ere étape
Créer le contrôleur et une vue minimale, et tester
Pour cela, créer une servlet MesCanauxServlet dans fr.siomassy2021.controller, avec
le chemin (utl) /mescanaux.
=> commit

2e étape
Mettre des canaux en dur dans le contrôleur,
et les afficher dans la JSP.
=> commit

3e étape
Appel de la Dao, qui construit la liste en dur
Le memberId est aussi mis en dur à 1
=> commit
'/
