@startuml
' par défaut, les couches sont disposées dans l'ordre d'apparition
' nous utilison participant pour préciser qu'après Navigateur il y a Vue et non Controleur
participant Navigateur
participant Vue

Navigateur -> Controleur: GET /presence?idSeance=..
Controleur -> Controleur: récupère user de la session
Controleur -> Dao: presenceDao.getByIdSeance(idSeance)
Dao -> SGBD: SELECT ...
SGBD -> Dao: lignes trouvées
Dao -> Controleur: Seance
Controleur -> Vue: presence.jsp
Vue -> Navigateur: html
Navigateur -> Controleur: POST /presence\navec idSeance
Controleur -> Dao: presenceDao.etudiantPresent(idSeance, idPersonne)
Dao -> SGBD: Insert ...
SGBD -> Dao: Insertion effectuée
Dao -> Controleur:ok ou exception si seance passee
Controleur -> Vue: presence.jsp
Vue -> Navigateur: html
@enduml

